services:
  postgres:
    image: postgres:17.1-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - serezin-gaming-postgres-dev:/var/lib/postgresql/data

volumes:
  serezin-gaming-postgres-dev:
